[build-system]
# Should be mirrored in requirements-build.txt
requires = [
    "ninja",
    "packaging",
    "setuptools >= 49.4.0",
    "torch ~= 2.2.0",
    "wheel",
]
build-backend = "setuptools.build_meta"
